### ISSUE TITLE
Number position on Flip card

### ISSUE THREAD

**Issue by JackyTung** [pqina/flip#31]
Hi, I want to know how to adjust number position in card.
I see "leading" property in demo page, but I can't find any related keyword or how to use in documentation 

<img width="1034" alt="螢幕快照 2021-04-21 上午12 09 15" src="https://user-images.githubusercontent.com/18186183/115429356-eb533f80-a235-11eb-8297-27cd400be641.png">

**Comment by rikschennink** [comment]
This is the code that the control generates
```css
.tick-flip-panel-text-wrapper {
   line-height: 2.4 !important; 
}
```
